-- No names, emails, IPs or typed queries. Receipts expire after 28 days.
CREATE TABLE catalog (url TEXT PRIMARY KEY, active INTEGER NOT NULL) WITHOUT ROWID;
CREATE TABLE receipts (day TEXT NOT NULL, uid TEXT NOT NULL, url TEXT NOT NULL, PRIMARY KEY(day,uid,url)) WITHOUT ROWID;
CREATE TABLE user_totals (day TEXT NOT NULL, uid TEXT NOT NULL, n INTEGER NOT NULL, PRIMARY KEY(day,uid)) WITHOUT ROWID;
CREATE TABLE day_totals (day TEXT PRIMARY KEY, n INTEGER NOT NULL) WITHOUT ROWID;
CREATE TABLE product_totals (day TEXT NOT NULL, url TEXT NOT NULL, n INTEGER NOT NULL, PRIMARY KEY(day,url)) WITHOUT ROWID;
CREATE TABLE state (key TEXT PRIMARY KEY, value TEXT NOT NULL) WITHOUT ROWID;
CREATE TRIGGER receipt_counts AFTER INSERT ON receipts BEGIN
  INSERT INTO user_totals VALUES (NEW.day,NEW.uid,1) ON CONFLICT(day,uid) DO UPDATE SET n=n+1;
  INSERT INTO day_totals VALUES (NEW.day,1) ON CONFLICT(day) DO UPDATE SET n=n+1;
  INSERT INTO product_totals VALUES (NEW.day,NEW.url,1) ON CONFLICT(day,url) DO UPDATE SET n=n+1;
END;
